Update DeployToEC2

diff --git a/.github/workflows/DeployToEC2 b/.github/workflows/DeployToEC2
--- a/.github/workflows/DeployToEC2
+++ b/.github/workflows/DeployToEC2
@@ -3,10 +3,10 @@ name: CI and Deploy Pipeline
 on:
   push:
     branches:
-      - main
+      - TestedBranch
   pull_request:
     branches:
-      - main
+      - TestedBranch
 
 jobs:
   build:
@@ -30,48 +30,35 @@ jobs:
           name: java-artifact
           path: target/*.war
 
-  deploy:
-    name: Deploy to EC2 on main branch push
-    runs-on: ubuntu-latest
+  trigger-jenkins-job:
     needs: build
+    runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout the files
-        uses: actions/checkout@v2
-
-      - name: Set up JDK 21
-        uses: actions/setup-java@v1
+      - name: Download Artifact
+        uses: actions/download-artifact@v3
         with:
-          java-version: '21'
+          name: java-artifact
+          path: ./artifacts
 
-      - name: Build with Maven
-        run: mvn clean package
+      - name: Check if artifact exists
+        run: |
+          if [ -f "./artifacts/java-artifact.war" ]; then
+            echo "Artifact found."
+          else
+            echo "Artifact not found. Exiting."
+            exit 1
+          fi
 
-      - name: Set Permissions on EC2
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            sudo mkdir -p /var/lib/tomcat9/webapps/
-            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} /var/lib/tomcat9/webapps/
-            sudo chmod -R 775 /var/lib/tomcat9/webapps/
+      - name: Get Jenkins Crumb
+        id: get-crumb
+        run: |
+          CRUMB=$(curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" -s "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" | jq -r '.crumb')
+          echo "::set-output name=crumb::$CRUMB"
 
-      - name: Deploy WAR to Server
-        uses: easingthemes/ssh-deploy@main
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
-          REMOTE_HOST: ${{ secrets.HOST_DNS }}
-          REMOTE_USER: ${{ secrets.USERNAME }}
-        with:
-          source: target/java-hello-app-1.0-SNAPSHOT.war
-          target: /var/lib/tomcat9/webapps/
-
-      - name: Restart Tomcat
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: sudo systemctl restart tomcat9
+      - name: Upload WAR to Jenkins and Trigger Job
+        run: |
+          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/buildWithParameters?token=${{ secrets.JENKINS_AUTH_TOKEN }}" \
+            -F "file=@./artifacts/java-artifact.war" \
+            -H "Jenkins-Crumb: ${{ steps.get-crumb.outputs.crumb }}" \
+            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
